In [16]:
import numpy as np
import pandas as pd

peppers = pd.read_csv("./data/labels.csv")
df = pd.DataFrame(peppers)
# unsure if I want to use the line below, it may potentially cause issues down the line
# df = df.set_index("pepper_id")

mild = df[:][:36]
medium = df[:][36:72]
hot = df[:][72:]
mild

   pepper_id  label            side1            side2
0       P001   mild   P001_side1.jpg   P001_side2.jpg
1       P002   mild   P002_side1.jpg   P002_side2.jpg
2       P003   mild   P003_side1.jpg   P003_side2.jpg
3       P004   mild   P004_side1.jpg   P004_side2.jpg
4       P005   mild   P005_side1.jpg   P005_side2.jpg
5       P006   mild   P006_side1.jpg   P006_side2.jpg
6       P007   mild   P007_side1.jpg   P007_side2.jpg
7       P008   mild   P008_side1.jpg   P008_side2.jpg
8       P009   mild   P009_side1.jpg   P009_side2.jpg
9       P010   mild   P010_side1.jpg   P010_side2.jpg
10      P011   mild   P011_side1.jpg   P011_side2.jpg
11      P012   mild   P012_side1.jpg   P012_side2.jpg
12      P013   mild   P013_side1.jpg   P013_side2.jpg
13      P014   mild   P014_side1.jpg   P014_side2.jpg
14      P015   mild   P015_side1.jpg   P015_side2.jpg
15      P016   mild   P016_side1.jpg   P016_side2.jpg
16      P017   mild   P017_side1.jpg   P017_side2.jpg
17      P018   mild   P018_side1.jpg   P018_side2.jpg
18      P019   mild   P019_side1.jpg   P019_side2.jpg
19      P020   mild   P020_side1.jpg   P020_side2.jpg
20      P021   mild   P021_side1.jpg   P021_side2.jpg
21      P022   mild   P022_side1.jpg   P022_side2.jpg
22      P023   mild   P023_side1.jpg   P023_side2.jpg
23      P024   mild   P024_side1.jpg   P024_side2.jpg
24      P025   mild   P025_side1.jpg   P025_side2.jpg
25      P026   mild   P026_side1.jpg   P026_side2.jpg
26      P027   mild   P027_side1.jpg   P027_side2.jpg
27      P028   mild   P028_side1.jpg   P028_side2.jpg
28      P029   mild   P029_side1.jpg   P029_side2.jpg
29      P030   mild   P030_side1.jpg   P030_side2.jpg
30      P031   mild   P031_side1.jpg   P031_side2.jpg
31      P032   mild   P032_side1.jpg   P032_side2.jpg
32      P033   mild   P033_side1.jpg   P033_side2.jpg
33      P034   mild   P034_side1.jpg   P034_side2.jpg
34      P035   mild   P035_side1.jpg   P035_side2.jpg
35      P036   mild   P036_side1.jpg   P036_side2.jpg

In [17]:
medium

   pepper_id    label            side1            side2
36      P037   medium   P037_side1.jpg   P037_side2.jpg
37      P038   medium   P038_side1.jpg   P038_side2.jpg
38      P039   medium   P039_side1.jpg   P039_side2.jpg
39      P040   medium   P040_side1.jpg   P040_side2.jpg
40      P041   medium   P041_side1.jpg   P041_side2.jpg
41      P042   medium   P042_side1.jpg   P042_side2.jpg
42      P043   medium   P043_side1.jpg   P043_side2.jpg
43      P044   medium   P044_side1.jpg   P044_side2.jpg
44      P045   medium   P045_side1.jpg   P045_side2.jpg
45      P046   medium   P046_side1.jpg   P046_side2.jpg
46      P047   medium   P047_side1.jpg   P047_side2.jpg
47      P048   medium   P048_side1.jpg   P048_side2.jpg
48      P049   medium   P049_side1.jpg   P049_side2.jpg
49      P050   medium   P050_side1.jpg   P050_side2.jpg
50      P051   medium   P051_side1.jpg   P051_side2.jpg
51      P052   medium   P052_side1.jpg   P052_side2.jpg
52      P053   medium   P053_side1.jpg   P053_side2.jpg
53      P054   medium   P054_side1.jpg   P054_side2.jpg
54      P055   medium   P055_side1.jpg   P055_side2.jpg
55      P056   medium   P056_side1.jpg   P056_side2.jpg
56      P057   medium   P057_side1.jpg   P057_side2.jpg
57      P058   medium   P058_side1.jpg   P058_side2.jpg
58      P059   medium   P059_side1.jpg   P059_side2.jpg
59      P060   medium   P060_side1.jpg   P060_side2.jpg
60      P061   medium   P061_side1.jpg   P061_side2.jpg
61      P062   medium   P062_side1.jpg   P062_side2.jpg
62      P063   medium   P063_side1.jpg   P063_side2.jpg
63      P064   medium   P064_side1.jpg   P064_side2.jpg
64      P065   medium   P065_side1.jpg   P065_side2.jpg
65      P066   medium   P066_side1.jpg   P066_side2.jpg
66      P067   medium   P067_side1.jpg   P067_side2.jpg
67      P068   medium   P068_side1.jpg   P068_side2.jpg
68      P069   medium   P069_side1.jpg   P069_side2.jpg
69      P070   medium   P070_side1.jpg   P070_side2.jpg
70      P071   medium   P071_side1.jpg   P071_side2.jpg
71      P072   medium   P072_side1.jpg   P072_side2.jpg

In [18]:
hot

    pepper_id label            side1            side2
72       P073   hot   P073_side1.jpg   P073_side2.jpg
73       P074   hot   P074_side1.jpg   P074_side2.jpg
74       P075   hot   P075_side1.jpg   P075_side2.jpg
75       P076   hot   P076_side1.jpg   P076_side2.jpg
76       P077   hot   P077_side1.jpg   P077_side2.jpg
77       P078   hot   P078_side1.jpg   P078_side2.jpg
78       P079   hot   P079_side1.jpg   P079_side2.jpg
79       P080   hot   P080_side1.jpg   P080_side2.jpg
80       P081   hot   P081_side1.jpg   P081_side2.jpg
81       P082   hot   P082_side1.jpg   P082_side2.jpg
82       P083   hot   P083_side1.jpg   P083_side2.jpg
83       P084   hot   P084_side1.jpg   P084_side2.jpg
84       P085   hot   P085_side1.jpg   P085_side2.jpg
85       P086   hot   P086_side1.jpg   P086_side2.jpg
86       P087   hot   P087_side1.jpg   P087_side2.jpg
87       P088   hot   P088_side1.jpg   P088_side2.jpg
88       P089   hot   P089_side1.jpg   P089_side2.jpg
89       P090   hot   P090_side1.jpg   P090_side2.jpg
90       P091   hot   P091_side1.jpg   P091_side2.jpg
91       P092   hot   P092_side1.jpg   P092_side2.jpg
92       P093   hot   P093_side1.jpg   P093_side2.jpg
93       P094   hot   P094_side1.jpg   P094_side2.jpg
94       P095   hot   P095_side1.jpg   P095_side2.jpg
95       P096   hot   P096_side1.jpg   P096_side2.jpg
96       P097   hot   P097_side1.jpg   P097_side2.jpg
97       P098   hot   P098_side1.jpg   P098_side2.jpg
98       P099   hot   P099_side1.jpg   P099_side2.jpg
99       P100   hot   P100_side1.jpg   P100_side2.jpg
100      P101   hot   P101_side1.jpg   P101_side2.jpg
101      P102   hot   P102_side1.jpg   P102_side2.jpg
102      P103   hot   P103_side1.jpg   P103_side2.jpg
103      P104   hot   P104_side1.jpg   P104_side2.jpg
104      P105   hot   P105_side1.jpg   P105_side2.jpg
105      P106   hot   P106_side1.jpg   P106_side2.jpg
106      P107   hot   P107_side1.jpg   P107_side2.jpg
107      P108   hot   P108_side1.jpg   P108_side2.jpg